power <- read.table(file = "/Users/mymac/Desktop/household_power_consumption.txt",header = TRUE,sep = ";",na.strings = "?")
power$Date <- as.Date(power$Date,'%d/%m/%Y')
startdate <- as.Date("2007-02-01")
enddate<- as.Date("2007-02-02")
new.power <- power[which(power$Date == startdate | power$Date == enddate),]
new.power[["Date/Time"]] <- paste(new.power$Date,' ',new.power$Time)
new.power[["Date/Time"]] <- strptime(new.power[["Date/Time"]],format = "%Y-%m-%d %H:%M:%S")
dev.new()
png(filename = "/Users/mymac/Desktop/plot4.png",width = 480, height = 480)
par(mfrow = c(2,2))
plot(new.power$`Date/Time`,new.power$Global_active_power, type = "l",xlab = "",ylab = "Global Active Power(kilowatts)" )
plot(new.power$`Date/Time`,new.power$Voltage,xlab = "datetime",ylab = "Voltage",main = "",type='l', )
plot(new.power$`Date/Time`,new.power$Sub_metering_1, col = 'black', type = "l",xlab = "",ylab = "Energy sub metering" )
lines(new.power$`Date/Time`,new.power$Sub_metering_2, col = 'red', type = "l",xlab = "",ylab = "Energy sub metering" )
lines(new.power$`Date/Time`,new.power$Sub_metering_3, col = 'blue', type = "l",xlab = "",ylab = "Energy sub metering" )
legend(x = "topright", c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black", "red", "blue"),lty = c(1,1,1) )
plot(new.power$`Date/Time`,new.power$Global_reactive_power, xlab = "datetime",ylab= "Global_reactive_power",type = 'l')
dev.off()
